'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ApplicationMDI.NET.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _00000000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000007() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000007", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000016() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000016", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000017() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000017", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000020() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000020", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000025() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000025", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000027() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000027", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000032() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000032", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000033() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000033", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000034() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000034", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000035() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000035", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000036() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000036", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000037() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000037", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000038() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000038", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000040() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000040", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000049() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000049", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000051() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000051", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _000000511() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("000000511", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000052() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000052", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000061() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000061", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000098() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000098", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000099() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000099", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000107() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000107", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000109() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000109", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000127() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000127", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000132() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000132", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000133() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000133", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000137() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000137", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000138() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000138", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000142() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000142", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000146() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000146", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000147() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000147", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000175() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000175", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000193() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000193", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000196() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000196", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000211() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000211", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000213() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000213", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000215() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000215", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000220() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000220", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000235() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000235", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000236() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000236", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000249() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000249", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000275() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000275", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000279() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000279", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000304() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000304", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000312() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000312", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000313() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000313", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000314() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000314", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000315() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000315", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000358() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000358", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000359() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000359", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000368() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000368", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000437() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000437", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000439() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000439", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000442() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000442", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000452() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000452", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000453() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000453", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000456() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000456", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000457() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000457", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000483() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000483", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000497() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000497", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000498() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000498", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000499() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000499", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000501() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000501", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000502() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000502", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000503() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000503", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000514() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000514", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _00000519() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("00000519", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmp7001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmp7001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
